data = {
    school: "General Assembly",
    city: "San Francisco",
    course: "Web Development Immersive",
    course_id: "WDI22",
    classrootm: "1",
    students: [{
        id: 0,
        last_name: "Aramayo",
        first_name: "Angelo",
        github_username: "angelo2dot0"
    }, {
        id: 1,
        last_name: "Bia",
        first_name: "Racha",
        github_username: "racha_bella"
    }, {
        id: 2,
        last_name: "Gabot",
        first_name: "Brian",
        github_username: "bgabot89"
    }, {
        id: 0,
        last_name: "Dawsom",
        first_name: "Chris",
        github_username: "awhit012"
    }, {
        id: 1,
        last_name: "Salinas",
        first_name: "Cynthia",
        github_username: "Cyndy528"
    }, {
        id: 2,
        last_name: "Zaghian",
        first_name: "Danielle",
        github_username: "DaniZaghian"
    }, {
        id: 0,
        last_name: "Long",
        first_name: "Francesca",
        github_username: "FrancescaLong"
    }, {
        id: 1,
        last_name: "Hollis",
        first_name: "Jamey",
        github_username: "HollisDayCheer"
    }, {
        id: 2,
        last_name: "Assaf",
        first_name: "Jason",
        github_username: "awhit012"
    }, {
        id: 0,
        last_name: "Kwok",
        first_name: "Jennifer",
        github_username: "jenniferkwok"
    }, {
        id: 1,
        last_name: "Shin",
        first_name: "Josh",
        github_username: "racha_bella"
    }, {
        id: 2,
        last_name: "Pangilinan",
        first_name: "Kenneth",
        github_username: "KennPangilinan"
    }, {
        id: 0,
        last_name: "Buitrago",
        first_name: "Laura",
        github_username: "awhit012"
    }, {
        id: 1,
        last_name: "Evans",
        first_name: "Laura",
        github_username: "lauraevans99"
    }, {
        id: 2,
        last_name: "Luzuriaga",
        first_name: "Margaux",
        github_username: "margauxwithanx"
    }, {
        id: 0,
        last_name: "Cowles",
        first_name: "Matthew",
        github_username: "mpcowles726"
    }, {
        id: 1,
        last_name: "Pawell",
        first_name: "Mikey",
        github_username: "mikeypawell"
    }, {
        id: 2,
        last_name: "Gelwicks",
        first_name: "Riley",
        github_username: "awhit012"
    }{
        id: 2,
        last_name: "Wills",
        first_name: "Robert",
        github_username: "robwills127"
    }, {
        id: 0,
        last_name: "Kizer",
        first_name: "Sameul",
        github_username: "kizersam"
    }, {
        id: 1,
        last_name: "Chavez",
        first_name: "Uriel",
        github_username: "awhit012"
    }, {
        id: 2,
        last_name: "Cauthen",
        first_name: "Will",
        github_username: "willcauthen"
    }]
}